# Generated by Django 5.2.17 on 2026-09-17 15:35

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team_profiles_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='abroad',
            field=models.BooleanField(default=False, help_text='Reestrda koʻrsatiladi, xaritada emas.', verbose_name='Xorijda'),
        ),
        migrations.CreateModel(
            name='ProjectLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('qoraqalpogiston', 'Qoraqalpogʻiston Respublikasi'), ('andijon', 'Andijon viloyati'), ('buxoro', 'Buxoro viloyati'), ('jizzax', 'Jizzax viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('navoiy', 'Navoiy viloyati'), ('namangan', 'Namangan viloyati'), ('samarqand', 'Samarqand viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('toshkent', 'Toshkent viloyati'), ('fargona', 'Fargʻona viloyati'), ('xorazm', 'Xorazm viloyati'), ('toshkent_shahri', 'Toshkent shahri')], max_length=20, verbose_name='Hudud')),
                ('city_uz', models.CharField(blank=True, max_length=80, verbose_name='Shahar')),
                ('city_ru', models.CharField(blank=True, max_length=80)),
                ('city_en', models.CharField(blank=True, max_length=80)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('confidence', models.CharField(choices=[('high', 'Aniq'), ('medium', 'Taxminiy')], default='high', max_length=8, verbose_name='Ishonch')),
                ('evidence', models.TextField(blank=True, verbose_name='Asos (matndan)')),
                ('is_public', models.BooleanField(default=True, verbose_name='Xaritada koʻrsatish')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.project')),
            ],
            options={
                'verbose_name': 'Loyiha joyi',
                'verbose_name_plural': 'Loyihalar joyi',
                'ordering': ['project__order', 'pk'],
            },
            bases=(core.models.TranslatableMixin, models.Model),
        ),
    ]
