# Generated by Django 5.2.17 on 2026-09-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_project_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffcertificate",
            name="issuer_en",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="staffcertificate",
            name="issuer_ru",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="staffcertificate",
            name="title_en",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="staffcertificate",
            name="title_ru",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
