# Generated by Django 5.2.17 on 2026-09-26 07:18

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_staffcertificate_i18n"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ui", "Sahifa matni"),
                            ("widget", "Vidjet matni (forma, kalkulyator)"),
                        ],
                        default="ui",
                        max_length=8,
                        verbose_name="Turi",
                    ),
                ),
                ("key", models.TextField(unique=True, verbose_name="Kalit")),
                ("text_uz", models.TextField(blank=True, verbose_name="Oʻzbekcha")),
                ("text_ru", models.TextField(blank=True, verbose_name="Ruscha")),
                ("text_en", models.TextField(blank=True, verbose_name="Inglizcha")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sayt matni",
                "verbose_name_plural": "Sayt matnlari",
                "ordering": ["kind", "key"],
            },
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Vertikal 4:5 nisbat, kamida 1280×1600 px, JPG.",
                        upload_to="slides/",
                        verbose_name="Surat",
                    ),
                ),
                (
                    "kicker_uz",
                    models.CharField(
                        help_text="Masalan: «Energoaudit»",
                        max_length=60,
                        verbose_name="Yorliq",
                    ),
                ),
                ("kicker_ru", models.CharField(blank=True, max_length=60)),
                ("kicker_en", models.CharField(blank=True, max_length=60)),
                ("text_uz", models.CharField(max_length=200, verbose_name="Izoh")),
                ("text_ru", models.CharField(blank=True, max_length=200)),
                ("text_en", models.CharField(blank=True, max_length=200)),
                (
                    "alt_uz",
                    models.CharField(
                        blank=True,
                        help_text="Koʻzi ojizlar uchun: suratda nima tasvirlangan.",
                        max_length=200,
                        verbose_name="Surat tavsifi (alt)",
                    ),
                ),
                ("alt_ru", models.CharField(blank=True, max_length=200)),
                ("alt_en", models.CharField(blank=True, max_length=200)),
                (
                    "focus_y",
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text="Mobil ekranda surat kesilganda qaysi qism koʻrinsin: 0 — yuqori, 100 — past.",
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Kadr markazi (vertikal, %)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Koʻrsatilsin"),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Slayd",
                "verbose_name_plural": "Bosh sahifa slaydlari",
                "ordering": ["order", "pk"],
            },
            bases=(core.models.TranslatableMixin, models.Model),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Kvadrat PNG, 180×180 px.",
                null=True,
                upload_to="branding/",
                verbose_name="Brauzer belgisi (favicon)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_footer",
            field=models.ImageField(
                blank=True,
                help_text="Toʻq fonda koʻrinadigan oq variant, kamida 144×144 px.",
                null=True,
                upload_to="branding/",
                verbose_name="Logotip (pastki qism, oq)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_mark",
            field=models.ImageField(
                blank=True,
                help_text="Kvadrat PNG, kamida 88×88 px. Boʻsh boʻlsa standart logotip.",
                null=True,
                upload_to="branding/",
                verbose_name="Logotip (sarlavha)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Havola ulashilganda chiqadi, 1200×630 px.",
                null=True,
                upload_to="branding/",
                verbose_name="Ijtimoiy tarmoq surati (OG)",
            ),
        ),
    ]
