# Generated by Django 5.2.17 on 2026-09-26 07:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_site_texts_slides_branding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Kvadrat PNG, 180×180 px.",
                null=True,
                upload_to="branding/",
                validators=[core.models.validate_image_size],
                verbose_name="Brauzer belgisi (favicon)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_footer",
            field=models.ImageField(
                blank=True,
                help_text="Toʻq fonda koʻrinadigan oq variant, kamida 144×144 px.",
                null=True,
                upload_to="branding/",
                validators=[core.models.validate_image_size],
                verbose_name="Logotip (pastki qism, oq)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo_mark",
            field=models.ImageField(
                blank=True,
                help_text="Kvadrat PNG, kamida 88×88 px. Boʻsh boʻlsa standart logotip.",
                null=True,
                upload_to="branding/",
                validators=[core.models.validate_image_size],
                verbose_name="Logotip (sarlavha)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Havola ulashilganda chiqadi, 1200×630 px.",
                null=True,
                upload_to="branding/",
                validators=[core.models.validate_image_size],
                verbose_name="Ijtimoiy tarmoq surati (OG)",
            ),
        ),
        migrations.AlterField(
            model_name="slide",
            name="image",
            field=models.ImageField(
                help_text="Vertikal 4:5 nisbat, kamida 1280×1600 px, JPG.",
                upload_to="slides/",
                validators=[core.models.validate_image_size],
                verbose_name="Surat",
            ),
        ),
    ]
